/**
 * Persistence layer types — SQLite-backed.
 * Schema-versioned for future migrations.
 */

export const DB_NAME = 'vialroute_db';
export const SCHEMA_VERSION = 1;

// Legacy constants kept for migration reference only
export const LEGACY_STORAGE_KEY = 'vialroute_state';
export const LEGACY_MIGRATION_FLAG = 'vialroute_migration_sqlite_done';

/**
 * Fuente runtime ÚNICA de los tipos de evento. Tanto el union TypeScript
 * `EventType` como el `eventTypeEnum` Zod en `campaign-schema.ts` se
 * derivan de esta misma constante: cualquier alta/baja se hace aquí y
 * propaga automáticamente a tipado y validación.
 */
export const EVENT_TYPES = [
  'CAMPAIGN_CREATED',
  'CAMPAIGN_IMPORTED',
  'CAMPAIGN_EXPORTED',
  'ROUTE_LOADED',
  'TRACK_OPENED',
  'TRACK_CLOSED',
  'SEGMENT_STARTED',
  'SEGMENT_COMPLETED',
  'SEGMENT_SKIPPED',
  'SEGMENT_RESET',
  'SEGMENT_REPEATED',
  'SEGMENT_CANCELLED',
  'SEGMENT_STATUS_CHANGED',
  'INCIDENT_RECORDED',
  'NAV_STARTED',
  'NAV_STOPPED',
  'WORK_DAY_CHANGED',
  'HW_CONFIRM_F5',
  'HW_CONFIRM_F7',
  'HW_CONFIRM_F9',
  'NAV_STATE_CHANGED',
  'SEGMENT_CORRECTION_APPLIED',
  'SEGMENT_CORRECTION_REVERTED',
  'SEGMENT_REACTIVATED_FOR_FIELD',
  'SEGMENT_DUPLICATED',
  'MIGRATION_FROM_LOCALSTORAGE',
  // Trimble (fase 1)
  'TRIMBLE_MISSION_STARTED',
  'TRIMBLE_MISSION_CLOSED',
  'TRIMBLE_RUN_STARTED',
  'TRIMBLE_RUN_CLOSED',
  'TRIMBLE_RUN_INVALIDATED',
  'TRIMBLE_CAPTURE_STARTED',
  'TRIMBLE_CAPTURE_CLOSED',
  'TRIMBLE_CAPTURE_MARKED_PENDING_PROCESS',
  'TRIMBLE_CAPTURE_MARKED_REPEAT',
  'TRIMBLE_CAPTURE_MARKED_NON_CAPTURABLE',
  'TRIMBLE_INCIDENT_RECORDED',
  'TRIMBLE_DELIVERABLE_LINKED',
  'TRIMBLE_DELIVERABLE_UNLINKED',
  'TRIMBLE_QA_STATUS_SET',
  'TRIMBLE_MODE_ACTIVATED',
  'TRIMBLE_COPILOT_QUEUE_SENT',
  'TRIMBLE_COPILOT_QUEUE_UPDATED',
  'TRIMBLE_COPILOT_QUEUE_SEND_FAILED',
  'TRIMBLE_COPILOT_QUEUE_AUTO_SENT',
  'TRIMBLE_RECORDING_STARTED',
  'TRIMBLE_RECORDING_CLOSED',
  'TRIMBLE_RECORDING_INVALIDATED',
  'TRIMBLE_SEGMENT_AUTO_CAPTURED',
  'TRIMBLE_SEGMENT_PARTIAL_COVERAGE',
  'TRIMBLE_CURRENT_SEGMENT_DETECTED',
  // Trimble — selección operativa y overrides desde overlay
  'TRIMBLE_SEGMENT_OPERATIONAL_SELECTED',
  'TRIMBLE_SEGMENT_OPERATIONAL_DESELECTED',
  'TRIMBLE_SEGMENT_RESET_TO_PENDING',
  'TRIMBLE_SEGMENT_MANUAL_NO_CAPTURABLE',
  'TRIMBLE_SEGMENT_MANUAL_CAPTURED',
  'TRIMBLE_SEGMENT_DIRECTION_OVERRIDE_SET',
  'TRIMBLE_SEGMENT_CAPTURE_VOIDED',
  'TRIMBLE_COPILOT_SINGLE_SEGMENT_SENT',
  'TRIMBLE_COPILOT_SINGLE_SEGMENT_SEND_FAILED',
  // Checkpoints de misión Trimble (fase 2)
  'TRIMBLE_PRECHECK_COMPLETED',
  'TRIMBLE_SYSTEM_READY_CONFIRMED',
  'TRIMBLE_GPS_TIME_VALID_CONFIRMED',
  'TRIMBLE_STATIC_TAIL_CONFIRMED',
  'TRIMBLE_STATIC_TAIL_OVERRIDDEN',
  'TRIMBLE_DATA_OFFLOADED',
  'TRIMBLE_MISSION_METADATA_UPDATED',
  'TRIMBLE_RUN_METADATA_UPDATED',
  'TRIMBLE_TRAJECTORY_DELIVERABLE_LINKED',
  'TRIMBLE_TRAJECTORY_ACCEPTED',
  'TRIMBLE_TRAJECTORY_REJECTED',
] as const;

export type EventType = typeof EVENT_TYPES[number];

export interface PersistentEvent {
  eventId: string;
  timestamp: string; // ISO 8601
  eventType: EventType;
  workDay?: number;
  trackNumber?: number;
  segmentId?: string;
  payload?: Record<string, unknown>;
}

export interface CampaignExport {
  version: 1;
  exportedAt: string;
  appVersion: string;
  state: import('@/types/route').AppState;
  eventLog: PersistentEvent[];
}
